#!/bin/sh
# REF: https://github.com/Mango0x45/dotfiles/blob/d62026673b0b833f27b85f8a551cb646ae2bd751/.config/eww/scripts/active-workspace-listener

readonly IPC=$(./scripts/hyprland-getsocket)

hyprctl -j activeworkspace | jq -r '.name'
socat -u UNIX-CONNECT:"$IPC" - | sed -n 's/^workspace>>//p'
