#!/usr/bin/env bash

#vim
alias nano='nvim'
alias vim='nvim'
alias vi='nvim'

#curl
alias weather='curl wttr.in'
alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'

#install
alias pac='sudo pacman'
alias pacS='sudo pacman -S'
alias pacSy='sudo pacman -Sy'
alias pacSyu='sudo pacman -Syu'
alias pacR='sudo pacman -R'
alias aur='yay'
alias aurS='yay -S'
alias aurSy='yay -Sy'
alias aurSyu='yay -Syu'
alias aurR='yay -R'

#ripper
alias spotifyrip='spotify-ripper -u palembani@gmail.com'
alias yt='youtube-dl'
alias ytaudio='youtube-dl -x --audio-format'
alias xreload='xrdb ~/.Xresources'

#shortcuts
alias ytv='youtube-viewer'
alias gravit='~/my\ Files/Gravit/GravitDesigner.AppImage'
alias redoom='~/doom refresh'
alias rvim='sudo vim'
alias py='python'
alias ps2c='sudo sh $HOME/.scripts/ps2c'
alias cls='clear'
alias classprop='xprop WM_CLASS'
alias storagelist='lsblk -f'
alias ..='cd ..'
alias ...='cd ../..'
alias ls='exa --color=always'
alias ll='ls -alF'
alias l='ls -CF'
alias la='ls -a'
#config shortcuts
alias cfvim='vim $XDG_CONFIG_HOME/vim/vimrc'
alias cfbash='vim $HOME/.bashrc'
alias cfzsh='vim $HOME/.zshrc'
alias cfbsp='vim $XDG_CONFIG_HOME/bspwm/bspwmrc'
alias cfpoly='vim $XDG_CONFIG_HOME/polybar/config'
alias cfkeys='vim $XDG_CONFIG_HOME/sxhkd/sxhkdrc'
alias cfalias='vim $XDG_CONFIG_HOME/zsh/aliases'
#more shortcuts
alias htop='htop -t'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

#Git Aliases
alias gs='git status'
alias gaa='git add --all'
alias gcm='git commit -m'
alias gp='git push'
alias config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'

