#!/usr/bin/env bash

#sudo
[ "x$(pgrep startx)" = "x" ] && alias sudo='sudo ' || alias sudo='sudo --askpass '
alias doas='doas -- '

#sudo + vim, yea imagine having that powe- nvm
alias sudovim='sudoedit'

#vim
alias nano=nvim
alias vim=nvim
alias vimsudo='sudoedit /etc/sudoers'
alias vi=nvim
alias v=nvim

#mutt
alias mutt="neomutt"

#curl
alias weather='curl wttr.in'
alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'

#install
alias p='sudo pacman'
alias a='yay'

#ripper
alias spotifyrip='spotify-ripper -u palembani@gmail.com'
alias yt='youtube-dl --add-metadata'
alias yta='youtube-dl --add-metadata -x --audio-format'
alias crunchyroll-dl='youtube-dl --write-sub --sub-lang enUS --cookies="/home/ziro/Downloads/cookies.txt"'
alias xreload='xrdb $HOME/.config/Xresources'

#clean up
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'

#shortcuts
alias ytv='youtube-viewer'
alias gravit='~/my\ Files/Gravit/GravitDesigner.AppImage'
alias redoom='~/doom refresh'
alias rvim='sudo vim'
alias py='python'
alias ps2c='sudo sh $HOME/.scripts/ps2c'
alias cls='clear'
alias classprop='xprop WM_CLASS'
alias storagelist='lsblk -f'
alias ..='cd ..'
alias ...='cd ../..'
alias q='exit'

alias l='exa --color=always --group-directories-first' # my preferred listing
alias ls='exa --color=always --group-directories-first' # my preferred listing
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
alias lla='exa -al --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing
alias md='mkdir -p'
alias rd='rmdir'

alias reUSD='rm -rf /tmp/rate.html /tmp/rateUSD.txt'
alias upElearn='sh $HOME/.scripts/elearning-isitup.sh'
# alias old-ranger='ranger'
alias ranger='lf'
#alias mpv='mpv --geometry=1280x720'

#config shortcuts
alias cfvim='vim $XDG_CONFIG_HOME/vim/vimrc'
alias cfvimplug='vim $XDG_CONFIG_HOME/vim/vim_plug'
alias cfvimnix='vim $XDG_CONFIG_HOME/vim/vim_nix'
alias cfvimwin='vim $XDG_CONFIG_HOME/vim/vim_win'
alias cfvimuni='vim $XDG_CONFIG_HOME/vim/vim_uni'
alias cfbash='vim $HOME/.bashrc'
alias cfzsh='vim $XDG_CONFIG_HOME/zsh/.zshrc'
alias cfxres='vim $XDG_CONFIG_HOME/Xresources'
alias cfbsp='vim $XDG_CONFIG_HOME/bspwm/bspwmrc'
alias cfqtile='vim $XDG_CONFIG_HOME/qtile/config.py'
alias cfpoly='vim $XDG_CONFIG_HOME/polybar/config'
alias cfkeys='vim $XDG_CONFIG_HOME/sxhkd/sxhkdrc'
alias cfalias='vim $XDG_CONFIG_HOME/zsh/aliases'
alias cfbind='vim $XDG_CONFIG_HOME/zsh/keybinds'
alias cfprofile='vim $XDG_CONFIG_HOME/zsh/.zprofile'
alias cfxprofile='vim $XDG_CONFIG_HOME/xprofile'
alias cfcompt='vim $XDG_CONFIG_HOME/picom/picom.conf'
alias cfenv='vim $XDG_CONFIG_HOME/zsh/.zshenv'
alias cfmutt='vim $XDG_CONFIG_HOME/mutt/muttrc'
alias cfnews='vim $XDG_CONFIG_HOME/newsboat/urls'

#more shortcuts
alias htop='htop -t'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias mntfd='sudo mount -o gid=users,fmask=113,dmask=002'
alias umntfd='sudo umount'
alias cmatrix='unimatrix -n -s 96 -l 'o''
alias make-xanmod='env use_tracers=n use_numa=n use_pds=y use_ns=y makepkg -s'

#folder shortcut
alias cdclg='cd "$HOME/my Files/Kuliah/"'
alias cdwine='cd "$HOME/.local/share/wineprefixes/"'

#Git Aliases
alias gaa='git add -A'
alias gca='git commit --all'
alias gr='git rm'
alias gR='git restore'
alias gs='git status'
alias gp='git push'
alias gP='git pull'
alias gcl='git clone'
alias config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'

alias qn='vim $HOME/Documents/QuickNote'
