#!/bin/sh

# Packages that share the same name across distro
packages=(
	git
	zsh
	# signing tools for Secure Boot
	efitools
)

packages_ubuntu=(
	# signing tools for Secure Boot
	sbsigntool
)

packages_arch=(
	ffmpeg
	# required by firefox-based browser, without it firefox-based browser can't play video from certain website
	ffmpeg4.4
	opendoas
	##region For shell scripts
	bc
	jo
	jq
	socat
	##endregion
	# signing tools for Secure Boot
	sbsigntools
	net-tools
	# for nvim-treesitter
	tree-sitter
	tree-sitter-cli
	# mostly for rankmirrors
	pacman-contrib
	# because pyenv can't do virtualenv properly
	uv
)

packages_arch_aur=(
	floorp-bin
	spicetify-cli
	spicetify-marketplace-bin
)

packages_flatpak=(
	io.mrarm.mcpelauncher
	##region Roblox
	org.vinegarhq.Sober
	org.vinegarhq.Vinegar
	##endregion
)
