#!/bin/sh

packages=(
	git
	zsh
	# signing tools for Secure Boot
	efitools
)

packages_ubuntu=(
	# signing tools for Secure Boot
	sbsigntool
)

packages_arch=(
	opendoas
	# >> for shell scripts
	jo
	bc
	socat
	jq
	# << for shell scripts
	ffmpeg
	# required by firefox, without it firefox-based browser can't play video from certain website
	ffmpeg4.4
	# signing tools for Secure Boot
	sbsigntools
)

packages_arch_aur=(
	floorp-bin
)
