#!/bin/sh

# Packages that share the same name across distro
packages=(
	git
	zsh
	# signing tools for Secure Boot
	efitools
)

packages_ubuntu=(
	# signing tools for Secure Boot
	sbsigntool
)

packages_arch=(
	ffmpeg
	# required by firefox-based browser, without it firefox-based browser can't play video from certain website
	ffmpeg4.4
	opendoas
	# >> for shell scripts
	bc
	jo
	jq
	socat
	# << for shell scripts
	# signing tools for Secure Boot
	sbsigntools
)

packages_arch_aur=(
	floorp-bin
	spicetify-cli
	spicetify-marketplace-bin
)
