#!/bin/sh

prompt() {
	printf "$1"
	read INPUT
	case $INPUT in
		[yY] ) return 0 ;;
		* ) return 1 ;;
	esac;
}

prompt_pos() {
	printf "$1"
	read INPUT
	case $INPUT in
		[nN] ) return 0 ;;
		* ) return 1 ;;
	esac;
}
