#!/bin/bash

[ "${EUID:-$(id -u)}" -eq 0 ] || { >&2 echo "Please run this as root."; exit 1; }

echo """#!/bin/zsh

export ZDOTDIR=\"\${XDG_CONFIG_HOME:-\$HOME/.config}/zsh\"""" > /etc/__zshenv && \
mv -i /etc/__zshenv /etc/zshenv
ln -si /etc/zshenv /etc/zsh/zshenv
