#!/bin/sh
# REF: https://github.com/Mango0x45/dotfiles/blob/c3e4bf8/.config/eww/scripts/active-workspace-listener

readonly IPC="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"

report() {
	hyprctl -j monitors | jq -cr '[.[] | .activeWorkspace.id % 10]'
}

report
socat -u UNIX-CONNECT:"$IPC" - | while read -r _
do
	case "${_%>>*}" in
		workspace|moveworkspace)
			report
	esac
done
