#!/bin/sh

if [[ "$OSTYPE" == "linux-gnu" ]]; then
	export _JAVA_AWT_WM_NONREPARENTING=1

	# Disable auto-dim/autolock/screen saver
	xset s off -dpms

	# Set cpu-governor to performance (Sometime it still set to powersave)
	cpupower frequency-set -g performance

	# Slow app startup fix (for flatpaks)
	dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

	if [[ "1$(pidof dwm)" == "1" ]]; then
		echo
	else
		# Autostarts for DWM
		# fcitx5 -d &
		xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &
		unclutter &
		dunst &
		numlockx &
		lxpolkit &
	fi

	# Custom Resolutions
	xrandr --newmode "768x432"   25.75  768 792 864 960  432 435 440 450 -hsync +vsync
	xrandr --newmode "960x540"   40.75  960 992 1088 1216  540 543 548 562 -hsync +vsync
	xrandr --addmode VGA1 768x432
	xrandr --addmode VGA1 960x540
fi
