#! /bin/dash

sxhkd &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
compton &
$HOME/.scripts/launch-conky.sh &
$HOME/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

primaryB = "#60C0FF"

bspc config border_width                  2
bspc config focused_border_color "#60C0FF"
#bspc config normal_border_color $BORDER_NORMAL_COLOR
#bspc config active_border_color $BORDER_NORMAL_COLOR
bspc config active_border_color		  "#60C0ff"
#bspc config normal_border_color
bspc config window_gap                    8
bspc config top_padding                   30 
bspc config bottom_padding                0 
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a obs desktop='^3'
bspc rule -a URxvt:cmus desktop='^4'
bspc rule -a spotify desktop='^4'
bspc rule -a Spotify desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Kodi desktop='^3'
bspc rule -a feh state=floating
bspc rule -a lxappearance state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Steam desktop='^6'
bspc rule -a steam desktop='^6'
bspc rule -a gravitdesigner desktop='^8' state=floating
bspc rule -a GravitDesigner desktop='^8' state=floating
bspc rule -a electronplayer desktop='^3'
bspc rule -a mcpelauncher-client desktop='^6' state=monocle
bspc rule -a citra-qt desktop='^6'
bspc rule -a Citra desktop='^6'
bspc rule -a Citra:citra-qt desktop='^6'
bspc rule -a org-tlauncher-tlauncher-rmo-TLauncher:sun-awt-X11-XFramePeer desktop='^6'
bspc rule -a org-tlauncher-tlauncher-rmo-TLauncher desktop='^6'
bspc rule -a PCSX2 desktop='^6'
bspc rule -a whatsapp-nativefier-d52542 desktop='^9'
bspc rule -a TelegramDesktop:telegram-desktop desktop='^9'
bspc rule -a Brave-browser:brave-browser desktop='^2'
bspc rule -a Code:code desktop='^5'
bspc rule -a Wine:photoshop.exe desktop='^8'
bspc rule -a File-roller:file-roller state=floating
bspc rule -a PacketTracer7:PacketTracer7 desktop='^7' state=floating
bspc rule -a discord:discord desktop='^9'
bspc rule -a qTox:qtox desktop='^9'
bspc rule -a pr:pr desktop='^10'
bspc rule -a firefox:Toolkit desktop='^3' state=floating
bspc rule -a mpv:gl state=floating
