BLACK='\e[40m'
RED='\e[0;41m'
GREEN='\e[0;42m'
ORANGE='\e[0;43m'
BLUE='\e[0;44m'
PUR='\e[0;45m'
CYAN='\e[0;46m'
GRAY='\e[0;47m'
DGRAY='\e[48;5;0m'
LRED='\e[1;41m'
LGREEN='\e[1;42m'
YELLOW='\e[1;43m'
LBLUE='\e[1;44m'
LPUR='\e[1;45m'
LCYAN='\e[1;46m'
WHITE='\e[1;47m'
N='\033[0m'
echo "$(tput setaf 4)        dhhhhhhhhhhhhhhhd"
echo '        yooooooooooo+//+d'                  
echo '                  ds/+h'
echo '                ds/+h'
echo '              ds/+h     hoy'
echo '            ds/+h      hy'
echo '          ds/+h'
echo '        ds/+h     do+d'
echo '      ds/+h     do/od'
echo '    ds/+h     do/od'
echo '   y///oooooo+/od'
echo -e "   dddddddddddd         ${DGRAY}   ${LRED}   ${LGREEN}   ${YELLOW}   ${LBLUE}   ${LPUR}   ${LCYAN}   ${WHITE}   ${N}"
echo -e "                        ${BLACK}   ${RED}   ${GREEN}   ${ORANGE}   ${BLUE}   ${PUR}   ${CYAN}   ${GRAY}   ${N}"
