#!/bin/sh
#--- Option ------------------
lock=""
suspend=""
log_out=""
restart=""
shutdown=""
#--- Choices -----------------
choice="$shutdown
$restart
$lock
$suspend
$log_out"

chosen=$(echo -en "$choice" | rofi -selected-row 2 -dmenu -i -theme ~/.config/rofi/theme/Android/five.rasi)

case "$chosen" in
	$lock) slock;;
	$log_out) bspc quit ;;
	$suspend) systemctl suspend ;;
	$restart) systemctl reboot ;;
	$shutdown) systemctl poweroff ;;
esac
