#!/bin/sh
#--- Option ------------------
cancel=""
suspend=""
log_out=""
restart=""
shutdown=""
#--- Choices -----------------
choice="$cancel
$shutdown
$restart
$suspend
$log_out"

chosen=$(echo -en "$choice" | rofi -selected-row 0 -dmenu -i -theme ~/.config/rofi/theme/Android/five.rasi)

case "$chosen" in
	$cancel) ;;
	$log_out) bspc quit ;;
	$suspend) systemctl suspend ;;
	$restart) systemctl reboot ;;
	$shutdown) systemctl poweroff ;;
esac
